### ISSUE TITLE
The "original" argument must be of type Function

### ISSUE THREAD

**Issue by liuhui677** [g-plane/rize#13]
HMR] Waiting for update signal from WDS...
util.js?3022:602 Uncaught TypeError: The "original" argument must be of type Function
    at promisify (util.js?3022:602)
    at eval (index.js?6b55:11)
    at Object../node_modules/extract-zip/index.js (chunk-vendors.js:2648)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (BrowserFetcher.js?aafb:48)
    at Object../node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js (chunk-vendors.js:4435)
    at __webpack_require__ (app.js:849)
    at fn (app.js:151)
    at eval (Puppeteer.js?a657:23)
promisify @ util.js?3022:602
eval @ index.js?6b55:11
./node_modules/extract-zip/index.js @ chunk-vendors.js:2648
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ BrowserFetcher.js?aafb:48
./node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserFetcher.js @ chunk-vendors.js:4435
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ Puppeteer.js?a657:23
./node_modules/puppeteer/lib/cjs/puppeteer/node/Puppeteer.js @ chunk-vendors.js:4495
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ initialize-node.js?f01a:22
eval @ initialize-node.js:46
./node_modules/puppeteer/lib/cjs/puppeteer/initialize-node.js @ chunk-vendors.js:4411
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ node.js?461f:18
./node_modules/puppeteer/lib/cjs/puppeteer/node.js @ chunk-vendors.js:4423
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ cjs-entry.js?7206:28
./node_modules/puppeteer/cjs-entry.js @ chunk-vendors.js:3931
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ index.js?0e7a:14
eval @ index.js:2226
./node_modules/rize/dist/index.js @ chunk-vendors.js:4845
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/HelloWorld.vue?vue&type=script&lang=js&:2
./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/components/HelloWorld.vue?vue&type=script&lang=js& @ app.js:950
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ HelloWorld.vue?9697:1
./src/components/HelloWorld.vue?vue&type=script&lang=js& @ app.js:1101
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ HelloWorld.vue?f177:1
./src/components/HelloWorld.vue @ app.js:1089
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js&:2
./node_modules/cache-loader/dist/cjs.js?!./node_modules/babel-loader/lib/index.js!./node_modules/cache-loader/dist/cjs.js?!./node_modules/vue-loader/lib/index.js?!./src/App.vue?vue&type=script&lang=js& @ app.js:938
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ App.vue?c53a:1
./src/App.vue?vue&type=script&lang=js& @ app.js:1053
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ App.vue?bff9:1
./src/App.vue @ app.js:1041
__webpack_require__ @ app.js:849
fn @ app.js:151
eval @ main.js:11
./src/main.js @ app.js:1137
__webpack_require__ @ app.js:849
fn @ app.js:151
1 @ app.js:1150
__webpack_require__ @ app.js:849
checkDeferredModules @ app.js:46
(anonymous) @ app.js:925
(anonymous) @ app.js:928
Show 34 more frames
vue.runtime.esm.js?2b0e:8484 You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html

**Comment by g-plane** [comment]
Are there anywhere related to Rize?

**Comment by g-plane** [comment]
Closing due to no response.
