### ISSUE TITLE
Assertion seems to run only if element found

### ISSUE THREAD

**Issue by mightyiam** [g-plane/rize#3]
`assertSeeIn` (perhaps others, as well?) seems to fail silently, if element doesn't exist. So I have to use `assertElementVisible` (or `...exists`) before. Is this by design?

**Comment by g-plane** [comment]
If the element doesn't exist, an error will be thrown. See: https://github.com/GoogleChrome/puppeteer/blob/e236887bbbd015e46fe036ef1caf957b52d70251/lib/FrameManager.js#L371

**Comment by mightyiam** [comment]
Maybe it has to do with selector pseudo classes? I'm using `nth-of-type(n)`. Maybe a failing test would be in order, but the problem might be in Puppeteer, who knows.

**Comment by g-plane** [comment]
Is it possible that your test runner haven't caught asynchronous exceptions? Which test framework do you use?

**Comment by mightyiam** [comment]
No framework. This is a student assignment. Just expecting assertions to terminate the process. I understand the whole Node.js swallowing unhandled promise rejection issue. But I'm not seeing any warning, either.

**Comment by g-plane** [comment]
I have reproduced this bug.
