### ISSUE TITLE
Timeout in waitFor* should throw if reached?

### ISSUE THREAD

**Issue by mightyiam** [g-plane/rize#4]
Doesn't it always make send to throw when the timeout is reached?

In what case do we allow a timeout to be not an assertion that the element exists?

**Comment by g-plane** [comment]
😅So sorry I can't get your main point. Can you speak more clearly?

**Comment by mightyiam** [comment]
Timeouts should throw error. Maybe! Not certainly. What do you think?

Timeout should === error? I am not sure. What do you think?

**Comment by g-plane** [comment]
Timeout should be an error. BTW, at low level, puppeteer will throw an error if time is out.

**Comment by mightyiam** [comment]
If the problem is that rize is swallowing puppeteer errors, then the solution is that it just throws them again. Not global things.

**Comment by g-plane** [comment]
As it is fixed in https://github.com/g-plane/rize/commit/90ac5bd8a33e51d5e9b3f06022ef581a4de2f803, you can try it again.

**Comment by g-plane** [comment]
So sorry I haven't released the new version. So you can try once I released.

**Comment by g-plane** [comment]
I have released v0.7.0. Now you can try it.

**Comment by g-plane** [comment]
Close because of no response.
