### ISSUE TITLE
waitForNavigation seems broken

### ISSUE THREAD

**Issue by mightyiam** [g-plane/rize#5]
See example [here](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagewaitfornavigationoptions).

```js
rize
  .goto('http://example.com')
  .click('a[href="/about"')
  .waitForNavigation()
  // TIMEOUT <--
  .assertUrlIs('http://example.com/about') // PASS
```

```js
rize
  .goto('http://example.com')
  .waitForNavigation() // starts waiting *before* navigation and **times out** before navigation
  // TIMEOUT <--
  .click('a[href="/about"')
  .assertUrlIs('http://example.com/about') // FAIL (or pass? race condition?)
```

**Comment by g-plane** [comment]
Check for details: https://github.com/GoogleChrome/puppeteer/pull/2354

**Comment by g-plane** [comment]
Close because of no response.

**Comment by Jaaap** [comment]
See also https://github.com/GoogleChrome/puppeteer/issues/1412
This solution worked for me (in Puppeteer)
```
await Promise.all([
        page.waitForNavigation(),
        page.click('nav>a[href="/blah"]')
]);
```
Is there an equivalent in Rize?

**Comment by g-plane** [comment]
I'm not sure. Did they fix that issue at latest version?

**Comment by Jaaap** [comment]
I doubt it.
I'm running 1.18.0 and the problem is still there for me.

**Comment by g-plane** [comment]
I may need to investigate how to fix this at this side.

**Comment by Jaaap** [comment]
How can you tell the difference between a click that navigates to a new page and a click that does some JS on the page?

Here's a proposal: make a `clickAndWaitForNavigation` method (but maybe give it a shorter name ;-)

**Comment by g-plane** [comment]
Both methods are just calling Puppeteer's methods, nothing more.

That proposal may be considerable!

**Comment by Jaaap** [comment]
Just for completeness, this is how i do it in Rize now:
```
rize.execute(async function (browser, page) {
    await Promise.all([ page.waitForNavigation(), page.click('a[href="/blah"]') ]);
});
```

**Comment by g-plane** [comment]
Yes, we can implement like this into Rize. What about the method name? `clickAndWait`? Shorter but more readable is better.

**Comment by Jaaap** [comment]
`clickAndWait`
`clickToNavigate`
`clickAndNavigate`
`clickAndWaitForNavigation`
hard to choose...

**Comment by g-plane** [comment]
Another idea: add a new option to `click` method which allows to wait for navigation.

**Comment by Jaaap** [comment]
Ooooh yes that's even nicer.

**Comment by g-plane** [comment]
https://github.com/g-plane/rize/commit/163d3f7976e5c70ecabf5a2728bc6a37a34a9608 implemented this.

**Comment by Jaaap** [comment]
Awesome!
I made a comment on the commit (about the order of `click` and `waitForNavigation`).

**Comment by g-plane** [comment]
Done.
