### ISSUE TITLE
puppeteer should be a peer-dependency

### ISSUE THREAD

**Issue by transitive-bullshit** [g-plane/rize#6]
this allows users to specify which version of puppeteer they want to use, and this lib just has to state which versions of puppeteer it supports.

in general, large third-party dependencies like puppeteer are usually better off being peer deps.

**Comment by g-plane** [comment]
Have you checked the `package.json` of Rize? Puppeteer is already as a peer dependency.

**Comment by transitive-bullshit** [comment]
Weird, I'm using a chrome extension which lists deps/peerdeps/devdeps on GH pages, and it was wrong, but the package.json is definitely correct.  Sorry about that!

Also, I'll add rize to awesome-puppeteer shortly; just need to finish some work stuff up first.

**Comment by g-plane** [comment]
Thanks!
