### ISSUE TITLE
Why waitFor API not supported？

### ISSUE THREAD

**Issue by caoxiaoshuai1** [g-plane/rize#8]
Why waitFor API not supported？
In many situtation, waitForElement can't cover all scenes, it is original supported by puppeteer.
In the docs, all puppeteer API can be used correctly, but actually not.

**Comment by g-plane** [comment]
The `waitFor` API from puppeteer supports three cases, which supported in Rize.

- Wait for timeout. In this case you can use `sleep` method.
- Wait for element. In this case you can use `waitForElement` method.
- Wait for executing a code snippet. In this case you can use `waitForEvaluation` method.

Hope it helps.

**Comment by g-plane** [comment]
Closing this issue as it looks like the question has been answered.
